import type { ReactElement } from 'react'
import {
  Apple,
  Aws,
  Bitcoin,
  Css,
  Discord,
  Dribbble,
  Dropbox,
  Facebook,
  Flowbite,
  Github,
  Gitlab,
  Google,
  Html,
  Instagram,
  Laravel,
  Linkedin,
  Mastercard,
  MongoDb,
  Npm,
  ReactLogo,
  Reddit,
  Stackoverflow,
  Tailwind,
  Twitter,
  Visa,
  Vue,
  Whatsapp,
  Windows,
  X,
  Youtube,
  type BrandIconProps,
} from './brandIcons'

/**
 * Registry nama → komponen untuk semua logo brand.
 * Dipakai halaman dokumentasi untuk merender galeri ikon secara dinamis.
 */
export const brandIcons: [string, (props: BrandIconProps) => ReactElement][] = [
  ['apple', Apple],
  ['aws', Aws],
  ['bitcoin', Bitcoin],
  ['css', Css],
  ['discord', Discord],
  ['dribbble', Dribbble],
  ['dropbox', Dropbox],
  ['facebook', Facebook],
  ['flowbite', Flowbite],
  ['github', Github],
  ['gitlab', Gitlab],
  ['google', Google],
  ['html', Html],
  ['instagram', Instagram],
  ['laravel', Laravel],
  ['linkedin', Linkedin],
  ['mastercard', Mastercard],
  ['mongo-db', MongoDb],
  ['npm', Npm],
  ['react', ReactLogo],
  ['reddit', Reddit],
  ['stackoverflow', Stackoverflow],
  ['tailwind', Tailwind],
  ['twitter', Twitter],
  ['visa', Visa],
  ['vue', Vue],
  ['whatsapp', Whatsapp],
  ['windows', Windows],
  ['x', X],
  ['youtube', Youtube],
]
